(enhancement) add ability to create subscription policy
flatironhealth/fh-immuta-utils pull request #10
Opened 2020-11-18 20:20 UTC by chintanms

- Add parsing of subscription policy to PolicyConfig
- Enhance policies commandlet to create/update subscription in addition to data policies
- Add a test case for new subscription policy parsing code
- Update documentation with example to create subscription policy
- Up minor version

2020-11-19 15:06 UTC, zturechek requested changes
great work! very exciting that we will no longer need to manually create subscription policies in the UI anymore  🙌 . let me know if i can clarify any of the in-line comments.

2020-11-19 15:06 UTC, zturechek commented on doc/managing_policies.md
> +* **action** --> not subsribe data sources for everyone except when user is a member of group `group01`
typo: `subsribe`

2020-11-19 15:06 UTC, zturechek commented on doc/managing_policies.md
> +*Note*: To apply both data and subscription policies skip the `--type` argument which defaults to
nice

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/policy.py
> -        circumstances=make_policy_circumstance(tags=tags, tagger=tagger),
`build_policy_circumstance` was created when refactoring the data policy code since the subscription policy code still had a dependency on `make_policy_circumstance`. now that both data and subscription policy creation are relying on `build_policy_circumstance`, we can either: 

1. rename `build_policy_circumstance` back to `make_policy_circumstance`, repoint the references, and remove the existing `make_policy_circumstance`
2. just remove `make_policy_circumstance` entirely and keep the references to `build_policy_circumstance`

i think for consistency in the code, #1 makes the most sense

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/policy.py
> +        staged=bool(policy_config.get("staged", False))
Rethinking this now: maybe the default should be `True`, so that a policy doesn't go live by accident, requiring the user to explicitly say it isn't staged

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/tests/test_policy.py
> +def subscription_policy_actions_dict(data_policy_dict):
can we rename the pytest fixture `data_policy_dict` to `policy_dict` now that it includes subscription policies?

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/policy.py
> +    staged: bool = False
see comment on line 397 about making this `True`

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/policy.py
> +                allow_discovery=bool(action_grouping["allowDiscovery"]),
my mistake when talking about the boolean conversion here earlier. `bool()` evaluates the truthiness, so any non-empty, non-`None` value will return `True`, which we don't want. see here: https://docs.python.org/3/library/functions.html?highlight=bool#bool

for converting to boolean for `allowDiscovery` and `staged`, we could use a function like this:

```
def str2bool(v: str) -> bool:

   return str(v).lower() in ("true")
```

we may also want to add a `get()` here as well similar to `staged` below, and default to `False`

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/policy.py
> +        staged=bool(policy_config.get("staged", False))
also see comment on boolean conversion on line 372

2020-11-19 15:06 UTC, zturechek commented on fh_immuta_utils/tests/test_policy.py
> +    assert subscription_policy_staged_bool == True
im not sure i understand this test. if we go with that boolean conversion function i mentioned on line 372, we could test that it converts correctly

2020-11-19 21:16 UTC, chintanms commented on doc/managing_policies.md
> +* **action** --> not subsribe data sources for everyone except when user is a member of group `group01`
Fixed

2020-11-19 21:17 UTC, chintanms commented on fh_immuta_utils/policy.py
> -        circumstances=make_policy_circumstance(tags=tags, tagger=tagger),
Went with 1, deleted previous function and renamed existing, along with fixing all callers.

2020-11-19 21:18 UTC, chintanms commented on fh_immuta_utils/tests/test_policy.py
> +def subscription_policy_actions_dict(data_policy_dict):
Renamed

2020-11-19 21:18 UTC, chintanms commented on fh_immuta_utils/policy.py
> +    staged: bool = False
Made it `True` by default. Also created str2bool helper.

2020-11-19 21:19 UTC, chintanms commented on fh_immuta_utils/policy.py
> +                allow_discovery=bool(action_grouping["allowDiscovery"]),
Thanks for catching this! Using `distutils.util.strtobool` for `staged` and `allowDiscovery`

2020-11-19 21:24 UTC, yuvalherziger commented
From a brief read through the code, this looks good to me. To be on the safe side I'd just make sure that all of the models are aligned with the swagger docs. Otherwise looks great 👍

2020-11-19 21:24 UTC, chintanms commented on fh_immuta_utils/tests/test_policy.py
> +    assert subscription_policy_staged_bool == True
Wanted to test that this bool was being parsed correctly from the sample `subscription.yaml`
Yeah, in effect this tests the new str2bool function. Let me know if this is not valuable (adds noise) and I can remove it.

2020-11-19 21:24 UTC, chintanms commented on fh_immuta_utils/policy.py
> +        staged=bool(policy_config.get("staged", False))
Fixed

2020-11-20 18:16 UTC, zturechek commented on fh_immuta_utils/policy.py
> +    return bool(strtobool(v))
interesting that `strtobool` doesn't return `True` or `False`, but `1` and `0`. looks like someone tried to submit a fix for it but it was shot down: https://bugs.python.org/issue27721

2020-11-20 18:16 UTC, zturechek commented on fh_immuta_utils/tests/test_policy.py
> +    assert subscription_policy_staged_bool == True
i think we are missing the reference to `str2bool` then, since this is only pulling the `staged` value from the parsed yaml in `policy_dict`

2020-11-23 19:03 UTC, chintanms commented on fh_immuta_utils/tests/test_policy.py
> +    assert subscription_policy_staged_bool == True
Removed str2bool, doesn't seem to be needed as yaml.safe_load will convert string to bool behind the scenes.

2020-11-23 19:59 UTC, zturechek approved these changes
lgtm!

2020-11-23 22:22 UTC, jinoa-fh approved these changes

2020-11-23 22:39 UTC, merged